<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_Client</name>
   <tag></tag>
   <elementGuidId>2260fd79-03ee-4160-9a36-632460035866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;project&quot;]/fieldset[1]/div[1]//preceding-sibling::select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;project&quot;]/fieldset[1]/div[1]//preceding-sibling::select</value>
   </webElementProperties>
</WebElementEntity>
