<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Endeavour</name>
   <tag></tag>
   <elementGuidId>3a12c0c5-7e01-4ad7-a442-1be3b7f29eb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/ul/li[1]/a[contains(text(),'Endeavour')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/ul/li[1]/a[contains(text(),'Endeavour')]</value>
   </webElementProperties>
</WebElementEntity>
