<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>9277ea85-bdcf-448d-b2ef-c832e2ce939c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-project-wbs/fieldset/div[1]/div[1]/div[3]/div/div[1]/div[1]/div[3]//button[contains(text(),'Add')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-project-wbs/fieldset/div[1]/div[1]/div[3]/div/div[1]/div[1]/div[3]//button[contains(text(),'Add')]</value>
   </webElementProperties>
</WebElementEntity>
