<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clear_Date_Picker</name>
   <tag></tag>
   <elementGuidId>43a9add3-6be8-4ede-b643-e5b2a901c1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;project&quot;]/div[1]/div[1]/div[3]/div/div[2]/p-calendar/span/div/div[2]/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;project&quot;]/div[1]/div[1]/div[3]/div/div[2]/p-calendar/span/div/div[2]/div/div[2]/button/span</value>
   </webElementProperties>
</WebElementEntity>
