<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_picker_calender</name>
   <tag></tag>
   <elementGuidId>51afc345-7177-45df-9b9d-d5b31e91b8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;project&quot;]/div[1]/div[1]/div[3]/div/div[2]/p-calendar/span/button/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;project&quot;]/div[1]/div[1]/div[3]/div/div[2]/p-calendar/span/button/span[1]</value>
   </webElementProperties>
</WebElementEntity>
