<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_DatePicker</name>
   <tag></tag>
   <elementGuidId>43983b1a-fcec-425d-96c1-b05562a75792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;project&quot;]/div[1]/div[1]/div[3]/div/div[2]/p-calendar/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;project&quot;]/div[1]/div[1]/div[3]/div/div[2]/p-calendar/span/input</value>
   </webElementProperties>
</WebElementEntity>
