<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Filter</name>
   <tag></tag>
   <elementGuidId>19387084-518d-4153-84fb-b3b814f5b777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-actionable-items/div[1]/div[1]/div[2]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-actionable-items/div[1]/div[1]/div[2]/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
