<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back</name>
   <tag></tag>
   <elementGuidId>5e268401-841b-496b-a22b-49a2f44f5930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/app-core/div/div[1]/div[2]/div/app-common/div/div[2]/app-assign-resource-to-positions/div/div/div/div[2]/div/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/app-core/div/div[1]/div[2]/div/app-common/div/div[2]/app-assign-resource-to-positions/div/div/div/div[2]/div/button[3]</value>
   </webElementProperties>
</WebElementEntity>
