<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Position_2</name>
   <tag></tag>
   <elementGuidId>1899fdd5-cba6-4e18-87cc-684a4ffd47cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/app-core/div/div[1]/div[2]/div/app-common/div/div[2]/app-assign-resource-to-positions/div/div/div/fieldset/div/app-multi-pos-to-res/div[1]/div[2]/p-datatable/div/div[1]/table/tbody/tr[2]/td[1]/p-dtcheckbox/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath1</name>
      <type>Main</type>
      <value>//tr[2]/td[1]/p-dtcheckbox/div/div[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/app-core/div/div[1]/div[2]/div/app-common/div/div[2]/app-assign-resource-to-positions/div/div/div/fieldset/div/app-multi-pos-to-res/div[1]/div[2]/p-datatable/div/div[1]/table/tbody/tr[2]/td[1]/p-dtcheckbox/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
