<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>128f4efd-cfbb-4d43-b643-a64c8237e72d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-pbi-wbs//div[3]//div[1]//button[contains(text(),'Add')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-pbi-wbs//div[3]//div[1]//button[contains(text(),'Add')]</value>
   </webElementProperties>
</WebElementEntity>
