<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arrow</name>
   <tag></tag>
   <elementGuidId>9b109ccd-540b-4fae-bee8-d4eac9ac0e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;accordion1&quot;]/p-accordion/div/p-accordiontab/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;accordion1&quot;]/p-accordion/div/p-accordiontab/div[1]/span</value>
   </webElementProperties>
</WebElementEntity>
