<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Endevour</name>
   <tag></tag>
   <elementGuidId>ef8f775a-ff2a-41b0-8a2d-3d914f7a27cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p-datatable/div/div[1]/table/thead/tr[2]/th[5]/span/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p-datatable/div/div[1]/table/thead/tr[2]/th[5]/span/div/input</value>
   </webElementProperties>
</WebElementEntity>
