<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TimeSheet_2</name>
   <tag></tag>
   <elementGuidId>1d71d8c0-6ac9-410a-b961-1c10a632670d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-work-sheet-grid/div/div/div/div[2]/p-datatable/div/div[1]/table/tbody/tr//span[2]/div/div/div[3]/div/span[1]/span[contains(text(),'03')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-work-sheet-grid/div/div/div/div[2]/p-datatable/div/div[1]/table/tbody/tr//span[2]/div/div/div[3]/div/span[1]/span[contains(text(),'03')]</value>
   </webElementProperties>
</WebElementEntity>
