<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submenu_Technology</name>
   <tag></tag>
   <elementGuidId>21ce2c75-8091-4e49-8803-fd4b44fa3143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbar-collapse-1&quot;]/div/ul/li/ul/li/ul/li/a[contains(text(),'Technology')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbar-collapse-1&quot;]/div/ul/li/ul/li/ul/li/a[contains(text(),'Technology')]</value>
   </webElementProperties>
</WebElementEntity>
