<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back</name>
   <tag></tag>
   <elementGuidId>66a6bf13-e987-4fcc-b27c-14893da8072e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-common/div/div[2]/app-sprint-wbs/div[3]/div//button[contains(text(),'Back')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-common/div/div[2]/app-sprint-wbs/div[3]/div//button[contains(text(),'Back')]</value>
   </webElementProperties>
</WebElementEntity>
