<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>72183d4a-bc00-4bab-adfa-e34742ceebf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//fieldset/div[1]/div[1]/div[3]/div/div/div[1]/div[3]/button[contains(text(),'Add')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//fieldset/div[1]/div[1]/div[3]/div/div/div[1]/div[3]/button[contains(text(),'Add')]</value>
   </webElementProperties>
</WebElementEntity>
