<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_tick</name>
   <tag></tag>
   <elementGuidId>b41f4d46-174e-4d87-915a-704901f22f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[14]/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[14]/div/a[2]/span</value>
   </webElementProperties>
</WebElementEntity>
