<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>2836fd88-222f-4d41-b2c2-1e192030f083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-view-update-compentency-popup/div[2]/div/button[contains(text(),'Close')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-view-update-compentency-popup/div[2]/div/button[contains(text(),'Close')]</value>
   </webElementProperties>
</WebElementEntity>
