<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>b85cfb4b-7487-4fdd-acd6-b0621da48bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-task-positions/fieldset//div[3]//button[contains(text(),'Add')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-task-positions/fieldset//div[3]//button[contains(text(),'Add')]</value>
   </webElementProperties>
</WebElementEntity>
